### ISSUE TITLE
Config keeps resetting if I change damage_power or damage_divisor

### ISSUE THREAD

**Issue by Jetpack-Cat** [x3rmination/skillrequirementgenerator#1]
What do the damage power and damage divisor do? 
Right now pretty much every sword in the modpack i'm making is saying it requires level 32, I need most of these swords to only require level 15 or so, changing damage divisor or damage power just resets the config when the game starts.

I would like to use this for a modpack because I have a lot of modded swords. The new modpack will be similar to my current modpack but only have melee weapons (https://www.curseforge.com/minecraft/modpacks/jetpack-cat)

**Comment by x3rdev** [comment]
As you can see from the config file the required level is defined as s^p / a
s being the value of the damage on the tool
p being a defined constant
d being a defined constant

**Comment by x3rdev** [comment]
Not added to config properly, will make change to reimplement
