### ISSUE TITLE
Crash: 

### ISSUE THREAD

**Issue by Jetpack-Cat** [x3rmination/skillrequirementgenerator#2]
This mod is making reskillable mod crash it looks like?

![image](https://user-images.githubusercontent.com/100042170/208799170-4ff1f81c-dede-46ab-876b-b477d23908ef.png)

[crash-2022-12-20_17.23.58-fml.txt](https://github.com/x3rmination/skillrequirementgenerator/files/10273787/crash-2022-12-20_17.23.58-fml.txt)

Latest version forge.

**Comment by x3rdev** [comment]
Fixed in newest update
